baseURL = "https://6011b36028223f7e9e833f2a--dazzling-poincare-1c9331.netlify.app/"
languageCode = "en-us"
title = "Dada Alaba Peter"
theme = "aafu"

[params]
    title = "Dada Alaba Peter"
    author = "Dada Alaba Peter"
    description = "Website title"
    copyright = "Peter Dada"

    [params.theme]
        # Available themes are 'light', 'dark', and 'pinkish'
        mainTheme = "dark"
        # setting false below will hide 'aafu by darshan' displayed under the profile pic
        showAttribute = true
        singlePage = false

    [params.favicons]
        use = true
        metas = '''
        <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
        <link rel="manifest" href="site.webmanifest">
        <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
        <link rel="shortcut icon" href="favicon.ico">
        '''

    # Profile section
    [params.profile]
        name = "Peter DADA."
		tagline = "Android Dev|GCP Enthusiast"
		location = "Ilaro, Ogun State"
        photo = "profile1.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
            class = "fab"
            icon = "fa-linkedin-in"
            url = "https://linkedin.com/in/dapetoo"
            title = "LinkedIn"		
        # [[params.social.list]]
        #     class = "fab"
        #     icon = "fa-stack-overflow"
        #     url = "#"
        #     title = "StackOverflow"
        [[params.social.list]]
            class = "fab"
            icon = "fa-github"
            url = "https://github.com/dapetoo"
            title = "GitHub"
        [[params.social.list]]
            class = "fab"
            icon = "fa-twitter"
            url = "https://twitter.com/dapetoo"
            title = "Twitter"
		# [[params.social.list]]
        #     class = "ai"
        #     icon = "ai-google-scholar"
        #     url = "#"
        #     title = "Google Scholar"
		# [[params.social.list]]
        #     class = "ai"
        #     icon = "ai-researchgate"
        #     url = "#"
        #     title = "ResearchGate"

    #Specify what is showin in the Accordion
    [[params.showInAccordion]]
        item = "aboutme"
        expand = true   # true for the section that is initially expanded
    [[params.showInAccordion]]
        item = "experience"
    [[params.showInAccordion]]
        item = "education"
    [[params.showInAccordion]]
        item = "publication"
    [[params.showInAccordion]]
        item = "project"
    [[params.showInAccordion]]
        item = "skill"
    [[params.showInAccordion]]
        item = "hobby"

    [params.aboutme]
        title = "About Me"
        icon = "fas fa-user"
        description = "**H/CS/19/0651. Peter DADA**, is a talented Mobile App Developer with Digital Marketing experience. He has the ability to think through a problem coupled with the confidence to make ideas heard and a proven ability to maintain and enhance company software with the aim of improving operational functionality in line with business requirements."

    # # Experience section
    # [params.experience]
    #     title = "Experiences"
    #     icon = "fas fa-briefcase"

    #     [[params.experience.list]]
    #         position = "Deeee"
    #         dates = "2019 - *Present*"
    #         company = "Company Name"
    #         details = "Printed from desktop. Sent [emails](#). Called people using telephone. Drank water from office cooler. Ate donuts on people's birthdays."
    #     [[params.experience.list]]
    #         position = "Job Title"
    #         dates = "2018 - 2019"
    #         link = "#"
    #         company = "Company Name"

    # Education section
    [params.education]
        title = "Education"
        icon = "fas fa-graduation-cap"

        [[params.education.list]]
            degree = "HND in Computer Science"
            college = "The Federal Polytechnic, Ilaro, Ogun State"
            dates = "2019 - 2021"

        
        [[params.education.list]]
            degree = "OND in Computer Science"
            college = "Kwara State Polytechnic, Ilorin, Kwara State"
            dates = "2014 - 2016"
            
            # thesis_title = "Effect of humans on other humans: a study of human behavior."
            # thesis_link = "#"


    # Publication section
    [params.publication]
        title = "Blog"
        icon = "fas fa-book"
        #The order below determines the order in which the items appear in "Publications" section
        format = ["date", "authors", "title", "journal"]
        #If you don't want to group publications, comment the line below by adding # at the beginning
        types = ["Journal Articles", "Proceedings"]

        [[params.publication.list]]
            title = """\
            I am interested in studying computer science because I find it fascinating. When I was about to finishe my SSCE,I remembered visiting a sister, she has this big desktop in her house with Angry bird game installed on it, I love playing the game.  I was initially drawn to them because I fancied computer games. However, the more I operated with computers, the more I began to appreciate understanding how they work, discovering just how much they can do and the near limitless potential they hold. I can always remember the feeling of wanting to know just how computers worked, why they worked and what else they could do. \
            
            My journey into the IT world started after my SSCE where I enrolled to learn Desktop Publishing which covers the basics such as how to interact with the operating system, Microsoft Office suite and Graphics Design. After two months into my program, I learnt that the institute is running a 50percent discount for their professional programs, I met with my instructor to guide me through on the prerequisite knowledge for the professional courses, I had interest in Web Design, SPSS, AutoCad etc. 
            
            The meeting with my instructor opened my eyes to what opportunities lies ahead for those in the IT field, during our meeting he mentioned a term HTML (Hypertext Markup Language), and I could remembered using my phone to search for the term, and I discovered the site https://w3schools.com. I learnt the bascis of HTML, CSS and some programming languages on the website. I did not enrolled for any professional course but I made a decision to study Computer Science in higher institution. I started my career as a Computer Scientist in order to know the nitty gritty of computing at Kwara State Polytechnic, where I was introduced to different programming languages such as QBasic, Visual Basic, Java and some other courses that explained the important concept of computer such as Digital Electronics, Operating System, Hardware. 
            
            Life at The Federal Polytechnic, Ilaro. The Federal Polytechnic, Ilaro has helped me to understand some important concepts that's required to be successful in the world of IT, I have been able to connect with awesome people in the polytechnic and this has broaden my knowledge of different fields that are available in the IT field. I have come to learnt that IT can be use to drive any field in order to improve human life and the society at large."""


            authors = "F Last, F Second, P secondary"
            date = "2018"
            journal = "Journal of Field 52 (16), 9033-9044"
            link = "#"
            type = "Journal Articles"

        [[params.publication.list]]
            title = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
            authors = "F Last, F Second, P secondary"
            date = "2018"
            journal = "Journal of Field 52 (16), 9033-9044"
            link = "#"
            type = "Journal Articles"
		
        [[params.publication.list]]
            title = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
            authors = "F Last, F Second, P secondary"
            date = "2018"
            journal = "Journal of Field 52 (16), 9033-9044"
            link = "#"
            type = "Proceedings"

    # Project section
    [params.project]
        title = "Projects"
        icon = "fas fa-project-diagram"

        [[params.project.list]]
            title = "Currency Converter"
            url = "#"
            description = "Currency Converter is a simple application for both iOS and Android that helps you convert from a currency to another. It' was developed using Flutter framework. You can update the exchange rates every-time you want so you'll have always an up-to-date conversion."
        [[params.project.list]]
            title = "BMI Calculator"
            url = "#"
            description = "With this BMI Calculator you can calculate and evaluate your Body Mass Index (BMI) based on the relevant information on body weight, height, age and sex. Check your body stats to find your ideal weight, because overweight and obesity are risk factors for diseases such as hypertension, heart disease and diabetes. It can also be used to find your healthy weight if you want to lose weight or are on diet."
        # [[params.project.list]]
        #     title = "project"
        #     url = "#"
        #     description = "Description of the project"
        # [[params.project.list]]
        #     title = "project"
        #     url = "#"
        #     description = "Description of the project"            

    # Skill section
    [params.skill]
        title = "Skills"
        panelId = "skill-panel"
        icon = "fas fa-cogs"

        [[params.skill.list]]
            skill = "Lead Generation, Email Marketing"
            skillrating = 90
        [[params.skill.list]]
            skill = "Flutter Development"
            skillrating = 70
        [[params.skill.list]]
            skill = "WordPress Development"
            skillrating = 50
        [[params.skill.list]]
            skill = "Business Development"
            skillrating = 65
        [[params.skill.list]]
            skill = "Technical Support"
            skillrating = 79

    # # Hobby section
    # [params.hobby]
    #     title = "Hobbies"
    #     icon = "fas fa-gamepad"
		
    #     [[params.hobby.list]]		
	# 	    hobby = "Cooking"
    #     [[params.hobby.list]]		
	# 	    hobby = "Hiking"
    #     [[params.hobby.list]]		
	# 	    hobby = "Baking"